"""Generate the consumer you should have written, for a specific feed on a specific chain.

Every check :mod:`alchem_link.safety` looks for is a check somebody left out. The
tutorial consumer everyone starts from is four lines that ignore all of them::

    (, int256 price, , ,) = feed.latestRoundData();
    return uint256(price);

That compiles, works in testing, and is wrong in five separate ways — no staleness
bound, no positivity check, no completeness check, no carried-round check, and on an L2
no sequencer gate. This module emits the version with all of them, filled in with values
this package *read from the chain* rather than placeholders:

* the aggregator address, EIP-55 checksummed
* the measured heartbeat for that specific feed on that specific chain — not 3600
  everywhere, which is the constant that makes staleness checks decorative on Polygon
* the L2 sequencer uptime feed and grace period, included only when the target is a
  rollup, because on an L1 those lines are noise

The generated Solidity has no imports and no dependencies: the two interfaces are
declared inline, so it compiles on its own. Run ``alchem-link audit`` against the same
feed afterwards and the findings should be the ones this code already handles.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, Optional

from .feeds import STALENESS_TOLERANCE, Feed, get_feed
from .networks import DEFAULT_NETWORK, get_network
from .sequencer import GRACE_PERIOD_SECS, SEQUENCER_FEEDS, is_l2

LANGUAGES = ("solidity", "typescript", "python")


def _identifier(pair: str) -> str:
    """``ETH/USD`` → ``EthUsd``, safe to paste into a contract name."""
    parts = [p for p in pair.replace("-", "/").split("/") if p]
    return "".join(part.capitalize() for part in parts) or "Price"


@dataclass
class GeneratedConsumer:
    language: str
    pair: str
    network: str
    address: str
    heartbeat_secs: int
    code: str
    #: Checks the emitted code enforces, so the caller can diff against an audit.
    guards: tuple = ()

    def as_dict(self) -> Dict[str, Any]:
        return {
            "language": self.language,
            "pair": self.pair,
            "network": self.network,
            "address": self.address,
            "heartbeat_secs": self.heartbeat_secs,
            "guards": list(self.guards),
            "code": self.code,
        }


_SOLIDITY = '''// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

// Generated by alchem-link for {pair} on {network_label}.
// Address, decimals and heartbeat were read from the chain, not copied from a table.

interface AggregatorV3Interface {{
    function decimals() external view returns (uint8);
    function description() external view returns (string memory);
    function latestRoundData()
        external
        view
        returns (uint80 roundId, int256 answer, uint256 startedAt, uint256 updatedAt, uint80 answeredInRound);
}}
{sequencer_interface}
/// @notice Reads {pair} with the staleness, positivity and completeness checks that
///         `latestRoundData()` does not perform for you.
contract {contract_name}Consumer {{
    AggregatorV3Interface public constant FEED =
        AggregatorV3Interface({address});

    /// @dev Measured publish interval for this feed on {network_label}, plus {tolerance}% slack.
    ///      This value is per-feed and per-chain: the same pair is {heartbeat}s here and
    ///      can be an order of magnitude different elsewhere.
    uint256 public constant MAX_AGE = {max_age};
{sequencer_constants}
    error StalePrice(uint256 updatedAt, uint256 maxAge);
    error InvalidPrice(int256 answer);
    error IncompleteRound();
    error StaleRoundAnswer(uint80 answeredInRound, uint80 roundId);
{sequencer_errors}
    /// @return price The latest answer, guaranteed positive, complete and fresh.
    /// @return decimals The feed's own decimals — do not hardcode 1e8.
    function latestPrice() public view returns (int256 price, uint8 decimals) {{
{sequencer_check}
        (uint80 roundId, int256 answer, , uint256 updatedAt, uint80 answeredInRound) =
            FEED.latestRoundData();

        // A round that was started but never finalised reports updatedAt == 0.
        if (updatedAt == 0) revert IncompleteRound();

        // The feed answers happily whether the last publish was ten seconds or ten
        // hours ago. This is the check that makes the difference.
        if (block.timestamp - updatedAt > MAX_AGE) revert StalePrice(updatedAt, MAX_AGE);

        // A non-positive answer is never a real quote.
        if (answer <= 0) revert InvalidPrice(answer);

        // answeredInRound < roundId means this round carried an older answer forward.
        if (answeredInRound < roundId) revert StaleRoundAnswer(answeredInRound, roundId);

        return (answer, FEED.decimals());
    }}

    /// @notice Scale the answer to 18 decimals, the usual internal convention.
    function latestPriceScaled() external view returns (uint256) {{
        (int256 price, uint8 decimals) = latestPrice();
        return uint256(price) * (10 ** (18 - decimals));
    }}
}}
'''

_SEQUENCER_INTERFACE = '''
interface ISequencerUptimeFeed {
    function latestRoundData()
        external
        view
        returns (uint80 roundId, int256 answer, uint256 startedAt, uint256 updatedAt, uint80 answeredInRound);
}
'''

_SEQUENCER_CONSTANTS = '''
    /// @dev {network_label} is a rollup. A price feed keeps answering while the
    ///      sequencer is down, with a price frozen at the moment it stopped.
    ISequencerUptimeFeed public constant SEQUENCER =
        ISequencerUptimeFeed({sequencer_address});

    /// @dev Time the sequencer must have been back up before prices are trusted again.
    ///      The moment after a restart is the dangerous one: transactions queued during
    ///      the outage all execute at once, against a price that did not move.
    uint256 public constant GRACE_PERIOD = {grace};
'''

_SEQUENCER_ERRORS = '''    error SequencerDown();
    error GracePeriodNotOver(uint256 elapsed, uint256 required);
'''

_SEQUENCER_CHECK = '''        // Check the sequencer before the price. If it is down, the price is a fossil.
        (, int256 sequencerStatus, uint256 sequencerStartedAt, , ) = SEQUENCER.latestRoundData();

        // 0 == up, 1 == down.
        if (sequencerStatus != 0) revert SequencerDown();

        // startedAt == 0 marks an invalid round: the status is unknown, so treat it as down.
        if (sequencerStartedAt == 0) revert SequencerDown();

        uint256 sequencerUpFor = block.timestamp - sequencerStartedAt;
        if (sequencerUpFor <= GRACE_PERIOD) revert GracePeriodNotOver(sequencerUpFor, GRACE_PERIOD);
'''

_TYPESCRIPT = '''// Generated by alchem-link for {pair} on {network_label}.
// Values read from the chain: address, decimals and the measured heartbeat.

const FEED_ADDRESS = "{address}";
const MAX_AGE_SECONDS = {max_age}; // measured {heartbeat}s heartbeat + {tolerance}% slack
const LATEST_ROUND_DATA = "0xfeaf968c"; // keccak256("latestRoundData()")[:4]
const DECIMALS = "0x313ce567";          // keccak256("decimals()")[:4]

export interface PriceReading {{
  price: number;
  decimals: number;
  updatedAt: number;
  ageSeconds: number;
  roundId: bigint;
}}

async function ethCall(rpcUrl: string, to: string, data: string): Promise<string> {{
  const response = await fetch(rpcUrl, {{
    method: "POST",
    headers: {{ "Content-Type": "application/json" }},
    body: JSON.stringify({{
      jsonrpc: "2.0",
      id: 1,
      method: "eth_call",
      params: [{{ to, data }}, "latest"],
    }}),
  }});
  const body = await response.json();
  if (body.error) throw new Error(`eth_call failed: ${{body.error.message}}`);
  return body.result;
}}

/** Word `index` of an ABI payload, as a bigint. */
function word(payload: string, index: number): bigint {{
  const raw = payload.startsWith("0x") ? payload.slice(2) : payload;
  return BigInt("0x" + raw.slice(index * 64, (index + 1) * 64));
}}

/** Two's-complement int256 — Chainlink answers are signed. */
function toInt256(value: bigint): bigint {{
  const CEILING = 1n << 256n;
  return value >= 1n << 255n ? value - CEILING : value;
}}

/**
 * Read {pair}, rejecting anything a consumer must not act on.
 * Throws rather than returning a suspect number: a stale price that looks like a
 * live one is the failure mode worth engineering against.
 */
export async function read{contract_name}(rpcUrl: string): Promise<PriceReading> {{
  const [roundPayload, decimalsPayload] = await Promise.all([
    ethCall(rpcUrl, FEED_ADDRESS, LATEST_ROUND_DATA),
    ethCall(rpcUrl, FEED_ADDRESS, DECIMALS),
  ]);

  const roundId = word(roundPayload, 0);
  const answer = toInt256(word(roundPayload, 1));
  const updatedAt = Number(word(roundPayload, 3));
  const answeredInRound = word(roundPayload, 4);
  const decimals = Number(word(decimalsPayload, 0));

  if (updatedAt === 0) throw new Error("incomplete round: updatedAt is 0");
  if (answer <= 0n) throw new Error(`invalid answer: ${{answer}}`);
  if (answeredInRound < roundId) throw new Error("round carried an older answer forward");

  const ageSeconds = Math.floor(Date.now() / 1000) - updatedAt;
  if (ageSeconds > MAX_AGE_SECONDS) {{
    throw new Error(`stale: ${{ageSeconds}}s old, limit ${{MAX_AGE_SECONDS}}s`);
  }}

  return {{
    price: Number(answer) / 10 ** decimals,
    decimals,
    updatedAt,
    ageSeconds,
    roundId,
  }};
}}
'''

_PYTHON = '''"""Generated by alchem-link for {pair} on {network_label}."""
from alchem_link import client_for, read_feed

#: Measured heartbeat for this feed on this chain, plus {tolerance}% slack.
MAX_AGE_SECONDS = {max_age}
FEED_ADDRESS = "{address}"


def latest_{snake}() -> float:
    """Return the current {pair} price, or raise if it is not safe to act on.

    Raising rather than returning is deliberate: a caller that gets a number back has
    no way to notice it was stale, and the whole point of the check is that a stale
    answer looks exactly like a good one.
    """
    reading = read_feed("{pair}", network="{network}")

    if reading.answer_raw <= 0:
        raise ValueError(f"{pair} returned a non-positive answer: {{reading.answer_raw}}")
    if reading.carried_over:
        raise ValueError(f"{pair} round carried an older answer forward")
    if reading.age_secs > MAX_AGE_SECONDS:
        raise ValueError(
            f"{pair} is {{reading.age_secs}}s old, limit {{MAX_AGE_SECONDS}}s — refusing to trade"
        )
    return reading.price
'''


def generate_consumer(
    pair: str,
    network: str = DEFAULT_NETWORK,
    language: str = "solidity",
    feed: Optional[Feed] = None,
) -> GeneratedConsumer:
    """Emit a ready-to-compile consumer for one feed on one chain."""
    if language not in LANGUAGES:
        raise ValueError(f"unknown language '{language}'. Choose from: {', '.join(LANGUAGES)}")

    net = get_network(network)
    target = feed or get_feed(pair, network)
    max_age = target.stale_after_secs
    contract_name = _identifier(target.pair)
    tolerance = int(STALENESS_TOLERANCE * 100)

    guards = ["staleness", "positive answer", "complete round", "carried-round"]
    common = {
        "pair": target.pair,
        "network": net.key,
        "network_label": net.label,
        "address": target.address,
        "max_age": max_age,
        "heartbeat": target.heartbeat_secs,
        "tolerance": tolerance,
        "contract_name": contract_name,
        "snake": target.pair.replace("/", "_").replace("-", "_").lower(),
    }

    if language == "solidity":
        uptime = SEQUENCER_FEEDS.get(net.key)
        if is_l2(net.key) and uptime:
            guards.append("L2 sequencer uptime + grace period")
            code = _SOLIDITY.format(
                sequencer_interface=_SEQUENCER_INTERFACE,
                sequencer_constants=_SEQUENCER_CONSTANTS.format(
                    network_label=net.label,
                    sequencer_address=uptime,
                    grace=GRACE_PERIOD_SECS,
                ),
                sequencer_errors=_SEQUENCER_ERRORS,
                sequencer_check=_SEQUENCER_CHECK,
                **common,
            )
        else:
            code = _SOLIDITY.format(
                sequencer_interface="",
                sequencer_constants="",
                sequencer_errors="",
                sequencer_check="",
                **common,
            )
    elif language == "typescript":
        code = _TYPESCRIPT.format(**common)
    else:
        code = _PYTHON.format(**common)

    return GeneratedConsumer(
        language=language,
        pair=target.pair,
        network=net.key,
        address=target.address,
        heartbeat_secs=target.heartbeat_secs,
        code=code,
        guards=tuple(guards),
    )
