//! [`DecisionRecord`]: what the agent decided, on what evidence, under which preferences —
//! and a commitment that lets somebody else check the record was not edited afterwards.
//!
//! ## What this proves, and what it does not
//!
//! Say it plainly, because the failure mode of every "proof-carrying" claim is a reader who
//! assumes it proves more than it does:
//!
//! * **It proves** the record is internally consistent: the world, goal, hypotheses,
//!   projections, policy configuration and decision stored in this file are exactly the
//!   ones the stated commitment was computed over. Change a single projected term, a λ
//!   weight, or the chosen branch, and [`verify`] names the field that moved.
//! * **It does not prove** the world was really like that. An observer that misread a
//!   repository produces a perfectly verifiable record of a wrong observation. Provenance,
//!   not the digest, is what carries that — which is why the world state is committed
//!   *whole*, `Absent` arms and blind spots included.
//! * **It does not prove** the record is the original. A record and its commitment can both
//!   be regenerated by whoever holds the file. Binding to something the author does not
//!   control — a timestamp authority, an append-only log, the on-chain commitment path in
//!   `scema-bot-mesh` — is a separate step, and until it exists this is tamper-**evident**
//!   to a third party holding an earlier copy, not tamper-proof.
//!
//! That third bullet is why [`Commitment::root`] exists as a single 32-byte value: it is
//! the thing you would anchor, and it is cheap to publish.
//!
//! ## Why the whole world state is committed rather than a summary
//!
//! A digest over "42 files, 3 risks" would verify a decision while saying nothing about the
//! `Absent` provenance on the object that mattered. The interesting question a year later is
//! never "what did it decide" but "what could it see when it decided", and that answer only
//! survives if the unreadable parts are inside the commitment too.

use scema_policy::{Decision, DecisionConfig};
use scema_sim::Projection;
use scema_world::{Goal, Hypothesis, WorldState};
use serde::{Deserialize, Serialize};

use crate::canonical::{digest, digest_of_digests, Digest};

/// Digests over each committed part, plus the root binding them together.
///
/// Stored as hex strings rather than bytes so a record is readable in a terminal and
/// diffable in git — this file is meant to be pasted into an issue.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Commitment {
    pub world: String,
    pub goal: String,
    pub hypotheses: String,
    pub projections: String,
    pub policy: String,
    pub decision: String,
    /// Digest over the six above, with their field names. Anchor this.
    pub root: String,
}

/// One complete pass of the loop, preserved.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DecisionRecord {
    /// Short id from [`Commitment::root`]; what an operator types into `scema explain`.
    pub id: String,
    /// Unix seconds.
    pub at: i64,
    /// Runtime that produced this, e.g. `scema-omni/0.1.0`. Recorded because the meaning of
    /// a term can change between versions, and a record that cannot say which code wrote it
    /// cannot be re-read safely.
    pub runtime: String,
    pub world: WorldState,
    pub goal: Goal,
    pub hypotheses: Vec<Hypothesis>,
    pub projections: Vec<Projection>,
    pub decision: Decision,
    pub commitment: Commitment,
}

fn commit(
    world: &WorldState,
    goal: &Goal,
    hypotheses: &[Hypothesis],
    projections: &[Projection],
    policy: &DecisionConfig,
    decision: &Decision,
) -> (Commitment, Digest) {
    let w = digest(world);
    let g = digest(goal);
    let h = digest(&hypotheses);
    let p = digest(&projections);
    let pol = digest(policy);
    let d = digest(decision);
    let root = digest_of_digests(&[
        ("world", w),
        ("goal", g),
        ("hypotheses", h),
        ("projections", p),
        ("policy", pol),
        ("decision", d),
    ]);
    (
        Commitment {
            world: w.to_hex(),
            goal: g.to_hex(),
            hypotheses: h.to_hex(),
            projections: p.to_hex(),
            policy: pol.to_hex(),
            decision: d.to_hex(),
            root: root.to_hex(),
        },
        root,
    )
}

impl DecisionRecord {
    /// Seal a cycle into a record.
    ///
    /// The policy configuration is committed separately from the decision even though the
    /// decision embeds it, so that a verifier can report *which* of the two was altered.
    /// One digest over both would say only "something changed".
    pub fn seal(
        runtime: impl Into<String>,
        at: i64,
        world: WorldState,
        goal: Goal,
        hypotheses: Vec<Hypothesis>,
        projections: Vec<Projection>,
        decision: Decision,
    ) -> Self {
        let policy = decision.config;
        let (commitment, root) =
            commit(&world, &goal, &hypotheses, &projections, &policy, &decision);
        DecisionRecord {
            id: root.short(),
            at,
            runtime: runtime.into(),
            world,
            goal,
            hypotheses,
            projections,
            decision,
            commitment,
        }
    }
}

/// A field whose stored digest does not match its stored payload.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Mismatch {
    pub field: String,
    pub committed: String,
    pub recomputed: String,
}

/// The outcome of re-checking a record.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Verification {
    pub id: String,
    pub valid: bool,
    /// Empty when valid. Names every field that moved, not just the first — a report that
    /// stops at the first mismatch makes a two-field edit look like a one-field edit.
    pub mismatches: Vec<Mismatch>,
    /// True when the six part digests are all correct but the root over them is not, which
    /// means the root was rewritten without recomputing — the signature of a hand edit.
    pub root_only: bool,
}

/// Recompute every commitment in a record and compare.
pub fn verify(record: &DecisionRecord) -> Verification {
    let (recomputed, root) = commit(
        &record.world,
        &record.goal,
        &record.hypotheses,
        &record.projections,
        &record.decision.config,
        &record.decision,
    );
    let c = &record.commitment;

    let pairs: [(&str, &String, &String); 6] = [
        ("world", &c.world, &recomputed.world),
        ("goal", &c.goal, &recomputed.goal),
        ("hypotheses", &c.hypotheses, &recomputed.hypotheses),
        ("projections", &c.projections, &recomputed.projections),
        ("policy", &c.policy, &recomputed.policy),
        ("decision", &c.decision, &recomputed.decision),
    ];

    let mut mismatches: Vec<Mismatch> = pairs
        .iter()
        .filter(|(_, committed, recomputed)| committed != recomputed)
        .map(|(field, committed, recomputed)| Mismatch {
            field: (*field).to_string(),
            committed: (*committed).clone(),
            recomputed: (*recomputed).clone(),
        })
        .collect();

    let parts_ok = mismatches.is_empty();
    let root_hex = root.to_hex();
    let root_ok = c.root == root_hex;
    if !root_ok {
        mismatches.push(Mismatch {
            field: "root".into(),
            committed: c.root.clone(),
            recomputed: root_hex,
        });
    }

    // The id is derived from the root, so an id that does not match is the same class of
    // edit and must not pass quietly.
    let id_ok = record.id == root.short();
    if !id_ok {
        mismatches.push(Mismatch {
            field: "id".into(),
            committed: record.id.clone(),
            recomputed: root.short(),
        });
    }

    Verification {
        id: record.id.clone(),
        valid: mismatches.is_empty(),
        mismatches,
        root_only: parts_ok && !root_ok,
    }
}

/// A complete sealed cycle, shared by this module's tests and `store`'s.
///
/// Lives here rather than being duplicated so that a change to the record shape breaks one
/// fixture, not two that drift apart.
#[cfg(test)]
pub(crate) mod tests_support {
    use super::*;
    use scema_policy::decide;
    use scema_sim::{Simulator, StructuralSimulator};
    use scema_world::{
        Action, Domain, Entity, EntityKind, Extent, HypothesisOrigin, Object, Polarity,
        Provenance, Reversibility, RiskClass, Signal,
    };

    pub(crate) fn sample() -> DecisionRecord {
        let world = WorldState {
            observer: "test".into(),
            entity: Entity { kind: EntityKind::Repository, locator: ".".into(), label: "t".into() },
            domain: Domain::Software,
            observed_at: 1_700_000_000,
            objects: vec![Object::new("o", "file", "o", Provenance::Live { age_secs: 0 })],
            facts: vec![],
            signals: vec![Signal {
                id: "s1".into(),
                polarity: Polarity::Opportunity,
                label: "untested crate".into(),
                detail: String::new(),
                magnitude: 0.8,
                measured: true,
                targets: vec![],
                evidence: vec!["0 test functions found".into()],
            }],
            extent: Extent::complete(1, "walked"),
            blind_spots: vec![],
        };
        let goal = Goal::new("g1", "raise confidence in this crate");
        let hs = vec![Hypothesis::new(
            "h1",
            "add tests",
            HypothesisOrigin::Heuristic { rule: "untested".into() },
        )
        .grounded("s1")
        .doing(Action::new("a1", RiskClass::Write, "tests/", "write", Reversibility::Trivial))];
        let ps = StructuralSimulator.project_all(&world, &goal, &hs);
        let d = decide(&world, &goal, &hs, &ps, &[], DecisionConfig::default());
        DecisionRecord::seal("scema-omni/test", 1_700_000_000, world, goal, hs, ps, d)
    }
}

#[cfg(test)]
mod tests {
    use super::tests_support::sample as cycle;
    use super::*;

    #[test]
    fn a_sealed_record_verifies() {
        let r = cycle();
        let v = verify(&r);
        assert!(v.valid, "{:?}", v.mismatches);
    }

    #[test]
    fn sealing_the_same_cycle_twice_gives_the_same_id() {
        // Determinism is the precondition for the whole scheme: a verifier can only compare
        // digests if the same inputs produce the same bytes.
        assert_eq!(cycle().id, cycle().id);
    }

    #[test]
    fn editing_the_world_is_caught_and_named() {
        let mut r = cycle();
        r.world.objects[0].label = "something else".into();
        let v = verify(&r);
        assert!(!v.valid);
        assert!(v.mismatches.iter().any(|m| m.field == "world"));
    }

    #[test]
    fn editing_a_projected_term_is_caught() {
        // The edit that matters: a plausible number quietly improved after the fact.
        let mut r = cycle();
        r.projections[0].expected_gain.value = 0.99;
        let v = verify(&r);
        assert!(!v.valid);
        assert!(v.mismatches.iter().any(|m| m.field == "projections"));
    }

    #[test]
    fn changing_the_lambda_weights_is_caught_separately_from_the_decision() {
        let mut r = cycle();
        r.decision.config.weights.risk = 0.01;
        let v = verify(&r);
        assert!(!v.valid);
        // Both move, because the decision embeds its config — and reporting both is the
        // point of committing them separately.
        assert!(v.mismatches.iter().any(|m| m.field == "policy"));
        assert!(v.mismatches.iter().any(|m| m.field == "decision"));
    }

    #[test]
    fn every_altered_field_is_reported_not_just_the_first() {
        let mut r = cycle();
        r.world.observer = "someone else".into();
        r.goal.statement = "a different goal".into();
        let v = verify(&r);
        assert!(v.mismatches.iter().any(|m| m.field == "world"));
        assert!(v.mismatches.iter().any(|m| m.field == "goal"));
    }

    #[test]
    fn rewriting_only_the_root_is_flagged_as_a_hand_edit() {
        let mut r = cycle();
        r.commitment.root = "0".repeat(64);
        let v = verify(&r);
        assert!(!v.valid);
        assert!(v.root_only, "parts all verify, so the root was edited on its own");
    }

    #[test]
    fn an_id_that_does_not_match_the_root_fails() {
        let mut r = cycle();
        r.id = "deadbeef".into();
        assert!(!verify(&r).valid);
    }

    #[test]
    fn a_record_survives_a_json_round_trip() {
        let r = cycle();
        let s = serde_json::to_string(&r).unwrap();
        let back: DecisionRecord = serde_json::from_str(&s).unwrap();
        assert!(verify(&back).valid, "a record that cannot be reloaded cannot be audited");
        assert_eq!(back, r);
    }
}
