/**
 * Verifying a decision record in the browser.
 *
 * Mirrors `scema_verify::record::verify`. Six part digests, then a root over them bound to
 * their field names, then the short id derived from the root.
 *
 * ## What a green badge here means, and what it does not
 *
 * The same three sentences as the Rust module, and they belong on the page rather than only
 * in a comment, because "VERIFIED" is exactly the kind of word a reader will over-read:
 *
 *  - It proves the record was not edited after sealing, and names the field that moved.
 *  - It does **not** prove the world was as described. An observer that misread a repository
 *    produces a perfectly verifiable record of a wrong observation. Provenance carries that.
 *  - It does **not** prove this is the original record. A record and its commitment can both
 *    be regenerated by whoever holds the file. Tamper-evident, not tamper-proof, until the
 *    root is anchored somewhere the author does not control.
 *
 * ## Everything here is local
 *
 * No network, no upload, no daemon. The record is read in the browser and hashed with
 * WebCrypto. A verifier that had to send the record somewhere to check it would be asking
 * the reader to trust a third party in order to avoid trusting one.
 */

import {
  canonicalBytes,
  fieldBytes,
  fromHex,
  parseCanonical,
  rootBytes,
  toHex,
  type CanonValue,
} from './canonical.ts'

/** The six committed parts, in the order Rust binds them into the root. */
export const COMMITTED_FIELDS = [
  'world',
  'goal',
  'hypotheses',
  'projections',
  'policy',
  'decision',
] as const

export type CommittedField = (typeof COMMITTED_FIELDS)[number]

export interface Mismatch {
  field: string
  committed: string
  recomputed: string
}

export interface Verification {
  id: string
  valid: boolean
  mismatches: Mismatch[]
  /** Parts all verify but the root does not — the root was rewritten on its own. */
  rootOnly: boolean
}

/** Injected so this module runs in a browser (WebCrypto) and in the check script (node). */
export type Sha256 = (bytes: Uint8Array) => Promise<Uint8Array>

/** WebCrypto. Available on https and on localhost; `crypto.subtle` is undefined otherwise. */
export const webSha256: Sha256 = async (bytes) => {
  if (typeof crypto === 'undefined' || !crypto.subtle) {
    throw new Error(
      'WebCrypto is unavailable. Decision records can only be verified over https or on localhost.'
    )
  }
  const buf = new Uint8Array(bytes)
  const digest = await crypto.subtle.digest('SHA-256', buf.buffer as ArrayBuffer)
  return new Uint8Array(digest)
}

function commitmentHex(root: CanonValue, field: string): string | null {
  if (root.t !== 'object') return null
  const commitment = root.v.find(([k]) => k === 'commitment')?.[1]
  if (!commitment || commitment.t !== 'object') return null
  const entry = commitment.v.find(([k]) => k === field)?.[1]
  return entry && entry.t === 'string' ? entry.v : null
}

function idOf(root: CanonValue): string | null {
  if (root.t !== 'object') return null
  const entry = root.v.find(([k]) => k === 'id')?.[1]
  return entry && entry.t === 'string' ? entry.v : null
}

/**
 * Recompute a record's commitment from its own payload.
 *
 * `text` is the raw file, not a parsed object: the integer/float distinction is only
 * present in the source text, and `JSON.parse` destroys it. See `canonical.ts`.
 */
export async function verifyRecordText(text: string, sha256: Sha256): Promise<Verification> {
  const root = parseCanonical(text)
  if (root.t !== 'object') {
    throw new Error('a decision record must be a JSON object')
  }

  const mismatches: Mismatch[] = []
  const digests: Array<[string, Uint8Array]> = []

  for (const field of COMMITTED_FIELDS) {
    // `policy` is not a top-level key: Rust commits `decision.config` under that name, so
    // that a verifier can report which of the two moved rather than only that something did.
    const bytes =
      field === 'policy' ? policyBytes(root) : fieldBytes(root, field)
    if (!bytes) {
      throw new Error(`record is missing the \`${field}\` payload`)
    }
    const digest = await sha256(bytes)
    digests.push([field, digest])

    const committed = commitmentHex(root, field)
    const recomputed = toHex(digest)
    if (committed === null) {
      throw new Error(`record commitment is missing \`${field}\``)
    }
    if (committed !== recomputed) {
      mismatches.push({ field, committed, recomputed })
    }
  }

  const partsOk = mismatches.length === 0

  const rootDigest = await sha256(rootBytes(digests))
  const rootHex = toHex(rootDigest)
  const committedRoot = commitmentHex(root, 'root')
  const rootOk = committedRoot === rootHex
  if (!rootOk) {
    mismatches.push({ field: 'root', committed: committedRoot ?? '(absent)', recomputed: rootHex })
  }

  const shortId = rootHex.slice(0, 8)
  const declaredId = idOf(root)
  if (declaredId !== shortId) {
    mismatches.push({ field: 'id', committed: declaredId ?? '(absent)', recomputed: shortId })
  }

  return {
    id: declaredId ?? shortId,
    valid: mismatches.length === 0,
    mismatches,
    rootOnly: partsOk && !rootOk,
  }
}

/** `decision.config`, which Rust commits separately under the name `policy`. */
function policyBytes(root: CanonValue): Uint8Array | null {
  if (root.t !== 'object') return null
  const decision = root.v.find(([k]) => k === 'decision')?.[1]
  if (!decision || decision.t !== 'object') return null
  const config = decision.v.find(([k]) => k === 'config')?.[1]
  return config ? canonicalBytes(config) : null
}

/** Convenience for a caller that already holds a hex digest to compare against. */
export function digestsMatch(a: string, b: string): boolean {
  if (a.length !== b.length) return false
  // Not timing-safe and does not need to be: both sides are public values in the reader's
  // own browser, and there is no secret to leak.
  return fromHex(a).every((byte, i) => byte === fromHex(b)[i])
}
