//! The numbers Scematica Zero must reproduce, emitted by the bot that owns them.
//!
//! `web/lib/zero/` runs the sniper's decision logic in a browser tab. It cannot link this
//! crate — solana-sdk does not compile to a page, and the pin comments in the root
//! `Cargo.toml` explain why the HTTP stack a browser build wants cannot coexist with it
//! anyway — so the logic is ported to TypeScript. Two implementations of one edge drift
//! unless that is managed, and the drift is silent: a mis-ported stop-loss does not throw,
//! it holds a losing position five percent longer.
//!
//! So this module emits every constant and every formula result Zero depends on, and
//! `web/scripts/check-zero.mjs` asserts the TypeScript reproduces them exactly. The
//! fixture is generated by the same code the sniper compiles — not typed out beside it —
//! which is the difference between this and a comment saying "keep these in sync".
//!
//! **Rust is authoritative.** A number changed here is a number Zero must follow, and the
//! test below fails until the fixture is regenerated:
//!
//!   cargo test -p scematica-sniper zero_parity                      (verify)
//!   ZERO_PARITY_WRITE=1 cargo test -p scematica-sniper zero_parity  (regenerate)
//!
//! ## What this pins, and what it does not
//!
//! It pins **values**: config constants, the rate-mode table, `KellySizer::compute_multiplier`
//! over a grid of histories, `coherence::assess` over a grid of degradations, the adaptive
//! pullback curve, and `PoolScorer::score` over a grid of pools.
//!
//! It does **not** pin control flow. The sell monitor's exit ladder is four hundred lines
//! inline in an async loop in `sniper.rs`; extracting it into a callable function would be
//! a large diff in a live buy-and-sell path, which is how a trading bug gets introduced by
//! a diagnostic. Zero's `exit-ladder.ts` is a hand port of that loop, and the gap between
//! the two is real — the same gap `scema-lean`'s README refuses to paper over. What the
//! fixture removes is the larger half of the risk: every threshold the ladder branches on
//! is checked here, so a ported rule can be wrong about *order* but not about *where it
//! fires*.

use std::path::PathBuf;

use scematica_core::config::{BotConfig, SniperConfig};
use serde_json::{json, Value};

use crate::cache::CachedPool;
use crate::coherence;
use crate::kelly::KellySizer;
use crate::pool_scorer::PoolScorer;

/// Where the fixture lands. Read by `web/scripts/check-zero.mjs`.
fn fixture_path() -> PathBuf {
    // CARGO_MANIFEST_DIR is `crates/scematica-sniper`.
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../web/lib/zero/fixtures/sniper-parity.json")
}

fn config_toml_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../config.toml")
}

/// The slice of `SniperConfig` Zero actually branches on.
///
/// Deliberately a hand-picked list rather than a blanket serialisation of the struct: a
/// dump would make every unrelated field a source of fixture churn, and a fixture that
/// changes for reasons nobody cares about is one people regenerate without reading.
fn config_slice(c: &SniperConfig) -> Value {
    json!({
        "quote_amount": c.quote_amount,
        "take_profit_pct": c.take_profit_pct,
        "stop_loss_pct": c.stop_loss_pct,
        "trailing_stop_loss_pct": c.trailing_stop_loss_pct,
        "buy_slippage_pct": c.buy_slippage_pct,
        "sell_slippage_pct": c.sell_slippage_pct,
        "price_check_interval_ms": c.price_check_interval_ms,
        "price_check_duration_ms": c.price_check_duration_ms,
        "max_concurrent_positions": c.max_concurrent_positions,
        "min_pool_score": c.min_pool_score,
        "kelly_sizing": c.kelly_sizing,
        "kelly_fraction": c.kelly_fraction,
        "kelly_lookback": c.kelly_lookback,
        "momentum_hold": c.momentum_hold,
        "momentum_window_checks": c.momentum_window_checks,
        "momentum_escalation_threshold_pct": c.momentum_escalation_threshold_pct,
        "momentum_escalation_factor": c.momentum_escalation_factor,
        "momentum_max_escalations": c.momentum_max_escalations,
        "momentum_min_peak_pct": c.momentum_min_peak_pct,
        "momentum_pullback_exit_pct": c.momentum_pullback_exit_pct,
        "adaptive_pullback": c.adaptive_pullback,
        "velocity_decay_exit": c.velocity_decay_exit,
        "velocity_decay_window": c.velocity_decay_window,
        "velocity_decay_min_pnl_pct": c.velocity_decay_min_pnl_pct,
        "velocity_decay_drop_threshold": c.velocity_decay_drop_threshold,
        "tiered_partial_tp": c.tiered_partial_tp,
        "tiered_partial_tp_levels": c.tiered_partial_tp_levels,
        "flash_crash_pct": c.flash_crash_pct,
        "profit_lock_checks": c.profit_lock_checks,
        "whale_exit_vault_drop_pct": c.whale_exit_vault_drop_pct,
        "volume_exhaustion_pct": c.volume_exhaustion_pct,
        "no_pump_timeout_secs": c.no_pump_timeout_secs,
        "no_pump_min_gain_pct": c.no_pump_min_gain_pct,
        "profit_first_mode": c.profit_first_mode,
        "profit_first_floor_pct": c.profit_first_floor_pct,
        "wallet_target_sol": c.wallet_target_sol,
        "max_position_hold_mins": c.max_position_hold_mins,
        "mint_cooldown_secs": c.mint_cooldown_secs,
        "coherence_breaker": c.coherence_breaker,
        "min_pool_size": c.filters.min_pool_size,
        "max_pool_size": c.filters.max_pool_size,
    })
}

fn rate_modes(c: &SniperConfig) -> Value {
    Value::Array(
        c.rate_modes
            .iter()
            .map(|m| {
                json!({
                    "name": m.name,
                    "order": m.order,
                    "quote_amount": m.quote_amount,
                    "wallet_pct": m.wallet_pct,
                    "take_profit_pct": m.take_profit_pct,
                    "stop_loss_pct": m.stop_loss_pct,
                    "momentum_max_escalations": m.momentum_max_escalations,
                    "enabled": m.enabled,
                })
            })
            .collect(),
    )
}

/// One Kelly grid entry: name, fraction, min_trades, and the `(profitable, pnl_sol)`
/// history the sniper's own sizer takes.
type KellyCase = (&'static str, f64, usize, Vec<(bool, f64)>);

/// `KellySizer::compute_multiplier` over the cases whose behaviour Zero must match.
///
/// The grid is chosen around the *discontinuities*, not around typical inputs: the
/// warm-up cliff at `min_trades`, the degenerate all-wins and all-losses returns, and
/// both clamp rails. A port can get the formula right and every one of those wrong.
fn kelly_cases() -> Value {
    let win = |n: usize, pnl: f64| -> Vec<(bool, f64)> { vec![(true, pnl); n] };
    let loss = |n: usize, pnl: f64| -> Vec<(bool, f64)> { vec![(false, pnl); n] };

    let mixed = |wins: usize, w: f64, losses: usize, l: f64| -> Vec<(bool, f64)> {
        let mut v = win(wins, w);
        v.extend(loss(losses, l));
        v
    };

    let cases: Vec<KellyCase> = vec![
        ("empty_history_is_base", 0.25, 10, vec![]),
        ("below_min_trades_is_half", 0.25, 10, mixed(3, 0.1, 2, 0.05)),
        ("exactly_min_trades_computes", 0.25, 10, mixed(6, 0.1, 4, 0.05)),
        ("all_wins_no_ratio_is_base", 0.25, 10, win(10, 0.1)),
        ("all_losses_no_ratio_is_base", 0.25, 10, loss(10, 0.1)),
        ("zero_magnitude_losses_ignored", 0.25, 10, mixed(5, 0.1, 5, 0.0)),
        ("strong_edge", 0.25, 10, mixed(14, 0.30, 6, 0.05)),
        ("weak_edge", 0.25, 10, mixed(6, 0.05, 14, 0.10)),
        ("clamps_low", 0.25, 10, mixed(1, 0.01, 19, 0.90)),
        ("clamps_high", 1.00, 10, mixed(19, 5.00, 1, 0.01)),
        ("half_kelly_fraction", 0.50, 10, mixed(14, 0.30, 6, 0.05)),
        ("min_trades_20", 0.25, 20, mixed(9, 0.20, 6, 0.05)),
    ];

    Value::Array(
        cases
            .into_iter()
            .map(|(name, fraction, min_trades, history)| {
                let k = KellySizer::with_min_trades(fraction, min_trades);
                json!({
                    "name": name,
                    "fraction": fraction,
                    "min_trades": min_trades,
                    "history": history.iter().map(|(p, v)| json!([p, v])).collect::<Vec<_>>(),
                    "multiplier": k.compute_multiplier(&history),
                })
            })
            .collect(),
    )
}

/// `coherence::assess` over a grid of degradations.
///
/// This is the fixture that matters most, because Ψ here is not the resolution rate — it
/// is the `scematica-sentience` master equation with the resolution rate threaded through
/// four of its terms. A port that reports the rate itself looks reasonable, tracks the
/// same direction, and crosses the gate at a completely different place.
fn coherence_cases() -> Value {
    let rates = [1.0_f64, 0.95, 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1, 0.0];
    let ages = [0.0_f64, 30.0, 90.0, 179.0, 180.0, 400.0];

    let mut out = Vec::new();
    for &rate in &rates {
        for &age in &ages {
            let (psi, gate) = coherence::assess(rate, age);
            out.push(json!({
                "resolution_rate": rate,
                "feed_age_secs": age,
                "psi": psi,
                "gate": gate.as_str(),
            }));
        }
    }
    Value::Array(out)
}

/// The adaptive pullback curve, theta_eff = base * sqrt(1 + peak/100).
fn adaptive_pullback_cases(base: f64) -> Value {
    let peaks = [-10.0_f64, 0.0, 20.0, 60.0, 100.0, 175.0, 200.0, 500.0, 1000.0];
    Value::Array(
        peaks
            .iter()
            .map(|&peak| {
                json!({
                    "peak_pnl_pct": peak,
                    "theta_eff": base * (1.0 + peak.max(0.0) / 100.0).sqrt(),
                })
            })
            .collect(),
    )
}

/// `PoolScorer::score` over a grid, with ages expressed as offsets from now.
///
/// The scorer reads the wall clock internally, so a fixture cannot pin an absolute
/// `open_time`. It can pin the *offset*: `open_time = now − age` makes both the age
/// ladder and the velocity signal deterministic, which is what a port has to reproduce.
fn pool_score_cases() -> Value {
    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();

    const SOL: f64 = 1_000_000_000.0;

    // (name, size_sol, age_offset_secs (None = open_time 0), base_vault_raw, pumpfun)
    let cases: Vec<(&str, f64, Option<u64>, u64, f64)> = vec![
        ("ghost_pool", 0.0, None, 0, 0.0),
        ("sub_1_sol", 0.5, Some(5), 0, 0.0),
        ("one_to_three_sol", 2.0, Some(5), 0, 0.0),
        ("thin_micro_cap", 7.0, Some(5), 0, 0.0),
        ("sweet_spot_ultra_fresh", 30.0, Some(5), 0, 0.0),
        ("sweet_spot_fresh", 30.0, Some(15), 0, 0.0),
        ("sweet_spot_marginal", 30.0, Some(35), 0, 0.0),
        ("sweet_spot_late", 30.0, Some(75), 0, 0.0),
        ("sweet_spot_very_late", 30.0, Some(150), 0, 0.0),
        ("sweet_spot_dead", 30.0, Some(400), 0, 0.0),
        ("unknown_age_fresh_detection", 30.0, None, 0, 0.0),
        ("migration_band", 60.0, Some(10), 0, 0.0),
        ("viable_band", 100.0, Some(10), 0, 0.0),
        ("established", 140.0, Some(10), 0, 0.0),
        ("whale_pool", 300.0, Some(10), 0, 0.0),
        ("buy_pressure_very_heavy", 30.0, Some(5), 100_000_000_000_000, 0.0),
        ("buy_pressure_clear", 30.0, Some(5), 250_000_000_000_000, 0.0),
        ("buy_pressure_mild", 30.0, Some(5), 500_000_000_000_000, 0.0),
        ("buy_pressure_neutral", 30.0, Some(5), 1_000_000_000_000_000, 0.0),
        ("buy_pressure_sell_skew", 30.0, Some(5), 5_000_000_000_000_000, 0.0),
        ("pumpfun_exceptional", 30.0, Some(5), 0, 95.0),
        ("pumpfun_strong", 30.0, Some(5), 0, 75.0),
        // The sigmoid saturates hard — `p` is an unnormalised product of likelihood
        // ratios, not a probability, so most healthy pools pin at exactly 100. That
        // saturation is worth pinning (a port that rolls off smoothly is wrong), but a
        // grid where fifteen of twenty-two cases read 100.0 cannot tell two ladders
        // apart. These sit in the band where the score actually discriminates.
        ("mid_band_thin_late", 12.0, Some(100), 0, 0.0),
        ("mid_band_thin_very_late", 12.0, Some(200), 0, 0.0),
        ("mid_band_micro_late", 5.0, Some(60), 0, 0.0),
        ("mid_band_whale_late", 200.0, Some(100), 0, 0.0),
        ("mid_band_sweet_spot_stale", 30.0, Some(130), 0, 0.0),
        ("mid_band_small_marginal", 8.0, Some(40), 0, 0.0),
        ("mid_band_risky_fresh", 4.0, Some(20), 0, 0.0),
        ("mid_band_established_dead", 160.0, Some(200), 0, 0.0),
        ("mid_band_pressure_swing", 12.0, Some(100), 400_000_000_000_000, 0.0),
        ("mid_band_pumpfun_rescue", 12.0, Some(200), 0, 85.0),
    ];

    Value::Array(
        cases
            .into_iter()
            .map(|(name, size_sol, age, base_vault, pumpfun)| {
                let pool = CachedPool {
                    id: Default::default(),
                    base_mint: Default::default(),
                    quote_mint: Default::default(),
                    base_vault: Default::default(),
                    quote_vault: Default::default(),
                    market_id: Default::default(),
                    open_time: age.map(|a| now.saturating_sub(a)).unwrap_or(0),
                    base_decimals: 6,
                    quote_decimals: 9,
                    pumpfun_score: pumpfun,
                };
                let size_lamports = (size_sol * SOL) as u64;
                json!({
                    "name": name,
                    "size_sol": size_sol,
                    // Zero receives an age, not an open_time. `null` is the open_time == 0
                    // case, which is not "age zero" — it is the pump.fun migration whose
                    // birth nobody recorded, and the scorer treats the two differently.
                    "age_secs": age,
                    "base_vault_raw": base_vault,
                    "pumpfun_score": pumpfun,
                    "score": PoolScorer::score(&pool, size_lamports, base_vault, now),
                })
            })
            .collect(),
    )
}

/// Build the whole fixture.
pub fn build() -> Value {
    let defaults = SniperConfig::default();
    let toml = BotConfig::from_file(config_toml_path())
        .expect("config.toml must parse — it is the config the bot actually runs")
        .sniper;

    json!({
        "note": "Generated by `cargo test -p scematica-sniper zero_parity`. Rust is \
                 authoritative; see crates/scematica-sniper/src/zero_parity.rs. Do not hand-edit.",
        "config_defaults": config_slice(&defaults),
        "config_toml": config_slice(&toml),
        "rate_modes": rate_modes(&toml),
        "active_mode_name": toml.active_mode_name,
        "coherence": {
            "window_secs": coherence::WINDOW_SECS,
            "min_samples": coherence::MIN_SAMPLES,
            "feed_stall_secs": coherence::FEED_STALL_SECS,
            "go_threshold": scematica_sentience::overlay::GO_THRESHOLD,
            "caution_threshold": scematica_sentience::overlay::CAUTION_THRESHOLD,
            "cases": coherence_cases(),
        },
        "kelly": {
            "default_fraction": defaults.kelly_fraction,
            "default_min_trades": 10,
            "clamp_min": 0.25,
            "clamp_max": 3.0,
            "cases": kelly_cases(),
        },
        "adaptive_pullback": {
            "base_default": defaults.momentum_pullback_exit_pct,
            "base_toml": toml.momentum_pullback_exit_pct,
            "cases": adaptive_pullback_cases(defaults.momentum_pullback_exit_pct),
        },
        "pool_score": {
            "cases": pool_score_cases(),
        },
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Report every leaf that differs, by path.
    ///
    /// A section-level report ("coherence differs") is not actionable on a fixture holding
    /// seventy-two cases, and the first version of this test shipped with one — which then
    /// could not explain a failure that turned out to be a float round-trip rather than a
    /// moved constant. A diff that cannot name the leaf sends somebody looking in the wrong
    /// file.
    fn diff(a: &Value, b: &Value, path: String, out: &mut Vec<String>) {
        match (a, b) {
            (Value::Object(x), Value::Object(y)) => {
                for (k, bv) in y {
                    match x.get(k) {
                        Some(av) => diff(av, bv, format!("{path}.{k}"), out),
                        None => out.push(format!("  {path}.{k}: absent in the fixture")),
                    }
                }
                for k in x.keys() {
                    if !y.contains_key(k) {
                        out.push(format!("  {path}.{k}: in the fixture, no longer emitted"));
                    }
                }
            }
            (Value::Array(x), Value::Array(y)) => {
                if x.len() != y.len() {
                    out.push(format!("  {path}: {} entries in the fixture, {} now", x.len(), y.len()));
                    return;
                }
                for (i, (av, bv)) in x.iter().zip(y).enumerate() {
                    diff(av, bv, format!("{path}[{i}]"), out);
                }
            }
            _ if a != b => out.push(format!("  {path}: fixture={a} now={b}")),
            _ => {}
        }
    }

    /// Emit the fixture, or fail naming what moved.
    ///
    /// Two modes on purpose. The default is a *comparison*, so a constant edited in
    /// `config.rs` breaks `cargo test` here rather than silently desynchronising a
    /// browser that nobody is going to rebuild. `ZERO_PARITY_WRITE=1` regenerates, which
    /// is the deliberate second keystroke — the same split as `simulate` and `decide`.
    #[test]
    fn zero_parity_fixture_is_current() {
        let built = super::build();
        let rendered = serde_json::to_string_pretty(&built).expect("fixture serialises");
        let path = fixture_path();

        if std::env::var("ZERO_PARITY_WRITE").is_ok() {
            if let Some(dir) = path.parent() {
                std::fs::create_dir_all(dir).expect("fixture directory");
            }
            std::fs::write(&path, format!("{rendered}\n")).expect("write fixture");
            eprintln!("wrote {}", path.display());
            return;
        }

        let existing = match std::fs::read_to_string(&path) {
            Ok(s) => s,
            Err(e) => panic!(
                "{} is missing ({e}). Regenerate with:\n  \
                 ZERO_PARITY_WRITE=1 cargo test -p scematica-sniper zero_parity",
                path.display()
            ),
        };

        // ── Compare the TEXT, not the parsed values ──────────────────────────────
        //
        // The obvious version of this test parsed the committed file and compared
        // `Value`s. It failed against a byte-identical file, on nine leaves out of several
        // hundred, all of them shaped like this:
        //
        //     fixture=11.31370849898476   now=11.313708498984761
        //
        // Not a moved constant — a round trip. `serde_json`'s *formatter* is exact, but its
        // *parser* is not correctly rounded for every 17-significant-digit input, so a
        // value it wrote itself can come back one ULP away. This repository has now hit
        // that wall three times: `scema-omni`'s canonical encoding (which answered it by
        // hashing fixed-point at 1e-9), `scema-bot-mesh`, and here.
        //
        // The artefact IS the text — that is what is committed, what `check:zero` reads,
        // and what a reviewer diffs — so comparing text is both simpler and stricter. It
        // also removes the ULP false positive completely rather than tolerating it, which
        // matters because a test that cries drift on an untouched file is one people learn
        // to regenerate without reading, and then it catches nothing.
        //
        // Whitespace sensitivity is the price and it is not a real cost: nothing hand-edits
        // this file, so the only way formatting moves is a `serde_json` upgrade, which is
        // worth being told about.
        //
        // (JavaScript is unaffected — its parser is correctly rounded — which is why
        // `check:zero` can compare these same numbers with `=== 0` tolerance and pass.)
        if existing.trim_end() == rendered.trim_end() {
            return;
        }

        // Past here something really moved. Parse both for a readable report, and say what
        // an empty report means rather than printing nothing and looking broken.
        let mut moved = Vec::new();
        match serde_json::from_str::<Value>(&existing) {
            Ok(old) => diff(&old, &built, String::from("$"), &mut moved),
            Err(e) => moved.push(format!("  the committed fixture does not parse: {e}")),
        }
        if moved.is_empty() {
            moved.push(
                "  no value differs — the change is formatting only (a serde_json upgrade?)"
                    .to_string(),
            );
        }
        moved.truncate(12);
        panic!(
            "the sniper's numbers have moved and Scematica Zero has not been told.\n{}\n\
             Regenerate, then run `npm run check:zero` in web/:\n  \
             ZERO_PARITY_WRITE=1 cargo test -p scematica-sniper zero_parity",
            moved.join("\n")
        );
    }
}
